/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Igor
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastrar = new javax.swing.JMenu();
        menuHospede = new javax.swing.JMenu();
        menuCadHospede = new javax.swing.JMenuItem();
        menuConHospede = new javax.swing.JMenuItem();
        menuQuarto = new javax.swing.JMenu();
        menuReserva = new javax.swing.JMenu();
        menuConsumo = new javax.swing.JMenu();
        menuFinanceiro = new javax.swing.JMenu();
        menuRelatorio = new javax.swing.JMenu();
        menuSeguranca = new javax.swing.JMenu();
        menuFerramenta = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastro.png"))); // NOI18N
        menuCadastrar.setText("Cadastro   |");

        menuHospede.setText("Hospede");

        menuCadHospede.setText("Cadastrar");
        menuHospede.add(menuCadHospede);

        menuConHospede.setText("Consultar");
        menuHospede.add(menuConHospede);

        menuCadastrar.add(menuHospede);

        menuQuarto.setText("Quarto");
        menuCadastrar.add(menuQuarto);

        jMenuBar1.add(menuCadastrar);

        menuReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/reservas.png"))); // NOI18N
        menuReserva.setText("Reservas   |");
        jMenuBar1.add(menuReserva);

        menuConsumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consumo.png"))); // NOI18N
        menuConsumo.setText("Consumo   |");
        jMenuBar1.add(menuConsumo);

        menuFinanceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/financeiro.png"))); // NOI18N
        menuFinanceiro.setText("Financeiro   |");
        jMenuBar1.add(menuFinanceiro);

        menuRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorios.png"))); // NOI18N
        menuRelatorio.setText("Relatorio   |");
        jMenuBar1.add(menuRelatorio);

        menuSeguranca.setText("Segurança   |");
        jMenuBar1.add(menuSeguranca);

        menuFerramenta.setText("Ferramenta   |");
        jMenuBar1.add(menuFerramenta);

        menuSair.setText("Sair");
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuCadHospede;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenuItem menuConHospede;
    private javax.swing.JMenu menuConsumo;
    private javax.swing.JMenu menuFerramenta;
    private javax.swing.JMenu menuFinanceiro;
    private javax.swing.JMenu menuHospede;
    private javax.swing.JMenu menuQuarto;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenu menuReserva;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuSeguranca;
    // End of variables declaration//GEN-END:variables
}
